# Generated by Django 4.2.5 on 2024-06-26 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_userprofile_is_vendo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_vendo',
            new_name='is_vendor',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
